#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export PATH=$HOME'/bin':$HOME'/opt/mvn2/bin':'/usr/local/share/npm/bin':$PATH
export LANG=en_US.UTF-8
export JAVA_HOME=`/usr/libexec/java_home --version 1.6`
export JAVA_HOME6=`/usr/libexec/java_home --version 1.6`
export JAVA_HOME7=`/usr/libexec/java_home --version 1.7`

alias jh6='export JAVA_HOME=$JAVA_HOME6'
alias jh7='export JAVA_HOME=$JAVA_HOME7'

export NODE_PATH=/usr/local/share/npm/bin

export KODE=$HOME/Customers/Forskningsradet/kode/
export SOLR_HOME=$HOME/opt/solr/

# alias runmongo='mongod run --config /usr/local/Cellar/mongodb/2.0.2-x86_64/mongod.conf'
alias ssbt='sbt -J"-noverify -javaagent:/Users/ovstetun/opt/JRebel/jrebel.jar -Drebel.lift_plugin=true"'

alias ems='javaws http://javazone.no/ems/webstart/launch.jnlp'

alias mci='mvn clean install'
alias mct='mvn clean test'

alias asadmin=/Users/ovstetun/opt/gf3/bin/asadmin

alias startpg='pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start'
alias stoppg='pg_ctl -D /usr/local/var/postgres -l logfile start'

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"
